services:
  mysql_dev:
    container_name: mysql_dev
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: chatly_dev
    volumes:
      - mysql_dev:/var/lib/mysql
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
      # - ./mysql/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - chatly_dev
  
  redis_dev:
    container_name: redis_dev
    image: redis
    ports:
      - "6380:6379"
    restart: always
    # environment:
    #   - REDIS_PASSWORD=mysecretpassword
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_dev:/data
    networks:
      - chatly_dev

volumes:
  mysql_dev:
  redis_dev:

networks:
  chatly_dev:
    driver: bridge