services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: chatly
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
      # - ./mysql/init:/docker-entrypoint-initdb.d
    restart: always
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    # environment:
    #   - REDIS_PASSWORD=mysecretpassword
    command: ["redis-server", "--appendonly", "yes"]
